server:
  port: 8081

aws:
  sns:
    platform_application:
      gcm: "arn:aws:sns:eu-central-1:144583872511:app/GCM/demo-application-android"
      apns: "arn:aws:sns:eu-central-1:144583872511:app/GCM/demo-application-ios"